# SPDX-License-Identifier: MIT
# Copyright (c) 2025-present K. S. Ernest (iFire) Lee

# Markdownlint configuration for aria-character-core
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# MD013: Line length - disabled to allow unlimited line length
MD013: false

# MD033: Inline HTML - allow HTML in markdown for better formatting
MD033: false

# MD041: First line in file should be a top level header - allow for license headers
MD041: false

# MD007: Unordered list indentation - use 2 spaces
MD007:
  indent: 2

# MD026: Trailing punctuation in header - allow for questions in headers
MD026:
  punctuation: ".,;:!"

# MD029: Ordered list item prefix - allow mixed numbering styles
MD029: false

# MD034: Bare URL used - allow bare URLs in documentation
MD034: false

# MD036: Emphasis used instead of a header - allow in ADRs for status
MD036: false

# MD040: Fenced code blocks should have a language specified
MD040: false

# MD046: Code block style - allow both indented and fenced
MD046: false

# MD049: Emphasis style - allow both * and _
MD049: false

# MD050: Strong style - allow both ** and __
MD050: false

# MD052: Reference links and images should use a label that is defined
MD052: false

# MD053: Link and image reference definitions should be needed
MD053: false

# Technical documentation specific rules
# Allow technical terms in code blocks and inline code
# These rules help with ADRs and technical documentation
