# SPDX-License-Identifier: MIT
# Copyright (c) 2025-present K. S. Ernest (iFire) Lee

repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5 # Use the latest appropriate version
    hooks:
      - id: insert-license
        name: Insert license headers (#-style comments)
        args:
          - "--license-filepath"
          - "LICENSE.short.md"
          - "--comment-style"
          - "#"
        files: \.(ex|exs|yaml|yml|py|sh|rb|pl)$
        exclude: ^(thirdparty/|deps/|_build/|LICENSE\.md$|.*\.md$|\.gitignore|\.gitattributes|\.tool-versions|.*\.json|.*\.html|.*\.css|.*\.js)

      - id: insert-license
        name: Insert license headers (#-style comments)
        args:
          - "--license-filepath"
          - "LICENSE.md"
          - "--comment-style"
          - "#"
        files: ^(justfile|Justfile)$
        exclude: ^(thirdparty/|deps/|_build/|LICENSE\.md$|.*\.md$|\.gitignore|\.gitattributes|\.tool-versions|.*\.json|.*\.html|.*\.css|.*\.js)

      - id: insert-license
        name: Insert license headers (//-style comments for C++)
        args:
          - "--license-filepath"
          - "LICENSE_HEADER.md"
          - "--comment-style"
          - "//"
        files: \.(cpp|hpp|h|cc|cxx|c)$
        exclude: ^(thirdparty/|deps/|_build/|LICENSE\.md$|LICENSE_HEADER\.txt$|.*\.md$|\.gitignore|\.gitattributes|\.tool-versions|.*\.json|.*\.html|.*\.css|.*\.js)
      - id: forbid-crlf  # Forbid files containing CRLF end-lines to be committed
      - id: remove-crlf  # Replace CRLF end-lines by LF ones before committing

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args: ["--fix", "--config", ".markdownlint.yaml"]
